// apps/nutriphi/apps/mobile/components/ui/Card.tsx
import React from 'react';
import { View, ViewProps } from 'react-native';

interface CardProps extends ViewProps {
	variant?: 'default' | 'elevated' | 'outline';
	children: React.ReactNode;
}

export const Card: React.FC<CardProps> = ({
	variant = 'default',
	children,
	className,
	...props
}) => {
	const baseStyles = 'rounded-xl p-4 bg-white';

	const variantStyles = {
		default: 'border border-gray-100',
		elevated: 'shadow-lg shadow-gray-200',
		outline: 'border-2 border-gray-200',
	};

	const combinedClassName = `${baseStyles} ${variantStyles[variant]} ${className || ''}`;

	return (
		<View className={combinedClassName} {...props}>
			{children}
		</View>
	);
};

// picture/apps/web/src/lib/components/ui/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		class?: string;
		padding?: boolean;
		children: Snippet;
	}

	let { class: className = '', padding = true, children }: Props = $props();

	const baseStyles = 'rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-900';
	const paddingStyles = padding ? 'p-6' : '';
	const cardClass = `${baseStyles} ${paddingStyles} ${className}`;
</script>

<div class={cardClass}>
	{@render children()}
</div>
