// apps-archived/wisekeep/apps/web/src/routes/(protected)/transcribe/+page.svelte
<script lang="ts">
	import { api } from '$lib/api/client';
	import { addJob } from '$lib/stores/jobs';
	import { goto } from '$app/navigation';

	let url = $state('');
	let language = $state('de');
	let provider = $state<'openai' | 'local'>('openai');
	let model = $state<'tiny' | 'base' | 'small' | 'medium' | 'large'>('base');
	let loading = $state(false);
	let error = $state<string | null>(null);

	const languages = [
		{ code: 'de', name: 'German' },
		{ code: 'en', name: 'English' },
		{ code: 'es', name: 'Spanish' },
		{ code: 'fr', name: 'French' },
		{ code: 'it', name: 'Italian' },
		{ code: 'pt', name: 'Portuguese' },
		{ code: 'ja', name: 'Japanese' },
		{ code: 'ko', name: 'Korean' },
		{ code: 'zh', name: 'Chinese' },
	];

	const models = [
		{ value: 'tiny', label: 'Tiny (39 MB, ~10x speed)' },
		{ value: 'base', label: 'Base (74 MB, ~7x speed)' },
		{ value: 'small', label: 'Small (244 MB, ~4x speed)' },
		{ value: 'medium', label: 'Medium (769 MB, ~2x speed)' },
		{ value: 'large', label: 'Large (1.5 GB, best accuracy)' },
	];

	async function handleSubmit(e: Event) {
		e.preventDefault();
		error = null;
		loading = true;

		try {
			const job = await api.createJob({
				url,
				language,
				provider,
				model: provider === 'local' ? model : undefined,
			});
			addJob(job);
			goto('/');
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to start transcription';
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>New Transcription | Wisekeep</title>
</svelte:head>

<div class="max-w-2xl mx-auto px-4 py-8">
	<h1 class="text-3xl font-bold mb-8">New Transcription</h1>

	{#if error}
		<div class="bg-red-50 text-red-600 p-4 rounded-lg mb-6">{error}</div>
	{/if}

	<form onsubmit={handleSubmit} class="bg-white rounded-lg shadow-sm border p-6 space-y-6">
		<div>
			<label for="url" class="block text-sm font-medium text-gray-700 mb-2"> YouTube URL </label>
			<input
				type="url"
				id="url"
				bind:value={url}
				placeholder="https://www.youtube.com/watch?v=..."
				required
				class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
			/>
		</div>

		<div>
			<label for="language" class="block text-sm font-medium text-gray-700 mb-2"> Language </label>
			<select
				id="language"
				bind:value={language}
				class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
			>
				{#each languages as lang}
					<option value={lang.code}>{lang.name}</option>
				{/each}
			</select>
		</div>

		<div>
			<label class="block text-sm font-medium text-gray-700 mb-2"> Transcription Provider </label>
			<div class="flex gap-4">
				<label class="flex items-center gap-2">
					<input type="radio" bind:group={provider} value="openai" />
					<span>OpenAI Whisper API</span>
				</label>
				<label class="flex items-center gap-2">
					<input type="radio" bind:group={provider} value="local" />
					<span>Local Whisper</span>
				</label>
			</div>
			<p class="text-sm text-gray-500 mt-1">
				{provider === 'openai'
					? 'Fast, cloud-based transcription (~$0.006/min)'
					: 'Free, requires local Whisper installation'}
			</p>
		</div>

		{#if provider === 'local'}
			<div>
				<label for="model" class="block text-sm font-medium text-gray-700 mb-2">
					Whisper Model
				</label>
				<select
					id="model"
					bind:value={model}
					class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
				>
					{#each models as m}
						<option value={m.value}>{m.label}</option>
					{/each}
				</select>
			</div>
		{/if}

		<button
			type="submit"
			disabled={loading || !url}
			class="w-full py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
		>
			{loading ? 'Starting...' : 'Start Transcription'}
		</button>
	</form>
</div>

// apps/transcriber/apps/mobile/app/(tabs)/transcribe.tsx
import { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  Pressable,
  ScrollView,
  Alert,
} from 'react-native';
import { router } from 'expo-router';
import { api } from '@/services/api';
import { useJobStore } from '@/stores/jobs';

export default function TranscribeScreen() {
  const [url, setUrl] = useState('');
  const [language, setLanguage] = useState('de');
  const [provider, setProvider] = useState<'openai' | 'local'>('openai');
  const [loading, setLoading] = useState(false);

  const addJob = useJobStore((state) => state.addJob);

  const languages = [
    { code: 'de', name: 'German' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Spanish' },
    { code: 'fr', name: 'French' },
  ];

  const handleSubmit = async () => {
    if (!url.trim()) {
      Alert.alert('Error', 'Please enter a YouTube URL');
      return;
    }

    setLoading(true);
    try {
      const job = await api.createJob({ url, language, provider });
      addJob(job);
      setUrl('');
      Alert.alert('Success', 'Transcription job started!', [
        { text: 'OK', onPress: () => router.push('/(tabs)/') },
      ]);
    } catch (error) {
      Alert.alert(
        'Error',
        error instanceof Error ? error.message : 'Failed to start transcription'
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.form}>
        <View style={styles.field}>
          <Text style={styles.label}>YouTube URL</Text>
          <TextInput
            style={styles.input}
            value={url}
            onChangeText={setUrl}
            placeholder="https://www.youtube.com/watch?v=..."
            autoCapitalize="none"
            autoCorrect={false}
            keyboardType="url"
          />
        </View>

        <View style={styles.field}>
          <Text style={styles.label}>Language</Text>
          <View style={styles.optionsRow}>
            {languages.map((lang) => (
              <Pressable
                key={lang.code}
                style={[
                  styles.option,
                  language === lang.code && styles.optionSelected,
                ]}
                onPress={() => setLanguage(lang.code)}
              >
                <Text
                  style={[
                    styles.optionText,
                    language === lang.code && styles.optionTextSelected,
                  ]}
                >
                  {lang.name}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>

        <View style={styles.field}>
          <Text style={styles.label}>Provider</Text>
          <View style={styles.optionsRow}>
            <Pressable
              style={[
                styles.option,
                provider === 'openai' && styles.optionSelected,
              ]}
              onPress={() => setProvider('openai')}
            >
              <Text
                style={[
                  styles.optionText,
                  provider === 'openai' && styles.optionTextSelected,
                ]}
              >
                OpenAI
              </Text>
            </Pressable>
            <Pressable
              style={[
                styles.option,
                provider === 'local' && styles.optionSelected,
              ]}
              onPress={() => setProvider('local')}
            >
              <Text
                style={[
                  styles.optionText,
                  provider === 'local' && styles.optionTextSelected,
                ]}
              >
                Local
              </Text>
            </Pressable>
          </View>
          <Text style={styles.hint}>
            {provider === 'openai'
              ? 'Fast, cloud-based transcription'
              : 'Free, requires local Whisper'}
          </Text>
        </View>

        <Pressable
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={handleSubmit}
          disabled={loading}
        >
          <Text style={styles.buttonText}>
            {loading ? 'Starting...' : 'Start Transcription'}
          </Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  form: {
    padding: 16,
  },
  field: {
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  option: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
  },
  optionSelected: {
    backgroundColor: '#9333ea',
    borderColor: '#9333ea',
  },
  optionText: {
    fontSize: 14,
    color: '#374151',
  },
  optionTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  hint: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 8,
  },
  button: {
    backgroundColor: '#9333ea',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
