// packages/shared-ui/src/atoms/Text.svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';

	type TextVariant = 'body' | 'body-secondary' | 'small' | 'large' | 'muted';
	type TextAlign = 'left' | 'center' | 'right';
	type TextWeight = 'normal' | 'medium' | 'semibold' | 'bold';

	interface Props extends HTMLAttributes<HTMLParagraphElement> {
		variant?: TextVariant;
		align?: TextAlign;
		weight?: TextWeight;
		class?: string;
		children?: any;
	}

	let {
		variant = 'body',
		align = 'left',
		weight = 'normal',
		class: className = '',
		children,
		...restProps
	}: Props = $props();

	const variantClasses: Record<TextVariant, string> = {
		body: 'text-base text-theme leading-relaxed',
		'body-secondary': 'text-base text-theme-secondary leading-relaxed',
		small: 'text-sm text-theme',
		large: 'text-lg text-theme leading-relaxed',
		muted: 'text-sm text-theme-muted'
	};

	const alignClasses: Record<TextAlign, string> = {
		left: 'text-left',
		center: 'text-center',
		right: 'text-right'
	};

	const weightClasses: Record<TextWeight, string> = {
		normal: 'font-normal',
		medium: 'font-medium',
		semibold: 'font-semibold',
		bold: 'font-bold'
	};

	const classes = $derived(
		`${variantClasses[variant]} ${alignClasses[align]} ${weightClasses[weight]} ${className}`
	);
</script>

<p class={classes} {...restProps}>
	{@render children?.()}
</p>

// apps/picture/packages/mobile-ui/components/ui/Text/Text.tsx
import { forwardRef } from 'react';
import { Text as RNText, TextProps as RNTextProps, TextStyle } from 'react-native';

export type TextVariant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'title'
  | 'body'
  | 'bodyLarge'
  | 'bodySmall'
  | 'caption'
  | 'label'
  | 'button';

export type TextWeight = 'regular' | 'medium' | 'semibold' | 'bold';

export type TextProps = {
  variant?: TextVariant;
  color?: string;
  weight?: TextWeight;
  align?: 'left' | 'center' | 'right';
  children?: React.ReactNode;
} & RNTextProps;

export const Text = forwardRef<RNText, TextProps>(({
  variant = 'body',
  color,
  weight,
  align = 'left',
  style,
  children,
  ...props
}, ref) => {
  const getVariantStyle = (): TextStyle => {
    switch (variant) {
      case 'h1':
        return { fontSize: 32, fontWeight: '700', lineHeight: 40 };
      case 'h2':
        return { fontSize: 28, fontWeight: '700', lineHeight: 36 };
      case 'h3':
        return { fontSize: 24, fontWeight: '600', lineHeight: 32 };
      case 'h4':
        return { fontSize: 20, fontWeight: '600', lineHeight: 28 };
      case 'title':
        return { fontSize: 44, fontWeight: '800', lineHeight: 52 };
      case 'bodyLarge':
        return { fontSize: 18, fontWeight: '400', lineHeight: 28 };
      case 'body':
        return { fontSize: 16, fontWeight: '400', lineHeight: 24 };
      case 'bodySmall':
        return { fontSize: 14, fontWeight: '400', lineHeight: 20 };
      case 'caption':
        return { fontSize: 12, fontWeight: '400', lineHeight: 16 };
      case 'label':
        return { fontSize: 14, fontWeight: '500', lineHeight: 20 };
      case 'button':
        return { fontSize: 16, fontWeight: '600', lineHeight: 24 };
      default:
        return {};
    }
  };

  const getFontWeight = (): TextStyle['fontWeight'] => {
    if (weight) {
      const weightMap: Record<TextWeight, TextStyle['fontWeight']> = {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      };
      return weightMap[weight];
    }
    return undefined;
  };

  const textStyle: TextStyle = {
    ...getVariantStyle(),
    ...(color && { color }),
    textAlign: align,
    ...(weight && { fontWeight: getFontWeight() }),
    ...(style as TextStyle),
  };

  return (
    <RNText ref={ref} style={textStyle} {...props}>
      {children}
    </RNText>
  );
});

Text.displayName = 'Text';
