// packages/shared-help-mobile/src/components/FeatureCard.tsx
/**
 * Feature Card component for mobile
 */

import React from 'react';
import { View, Text } from 'react-native';
import type { FeatureItem } from '@manacore/shared-help-types';

interface FeatureCardProps {
	item: FeatureItem;
	comingSoonLabel?: string;
}

export function FeatureCard({ item, comingSoonLabel = 'Coming soon' }: FeatureCardProps) {
	return (
		<View className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-3 border border-gray-200 dark:border-gray-700">
			<View className="flex-row items-center mb-2">
				{item.icon && <Text className="text-2xl mr-3">{item.icon}</Text>}
				<View className="flex-1">
					<View className="flex-row items-center">
						<Text className="font-semibold text-gray-900 dark:text-gray-100 text-base">
							{item.title}
						</Text>
						{item.comingSoon && (
							<View className="ml-2 bg-amber-100 dark:bg-amber-900/30 px-2 py-0.5 rounded-full">
								<Text className="text-xs text-amber-700 dark:text-amber-400">
									{comingSoonLabel}
								</Text>
							</View>
						)}
					</View>
				</View>
			</View>

			<Text className="text-gray-600 dark:text-gray-400 text-sm mb-2">{item.description}</Text>

			{item.highlights && item.highlights.length > 0 && (
				<View className="mt-2">
					{item.highlights.map((highlight, index) => (
						<View key={index} className="flex-row items-start mb-1">
							<Text className="text-green-500 mr-2">✓</Text>
							<Text className="text-gray-600 dark:text-gray-400 text-sm flex-1">{highlight}</Text>
						</View>
					))}
				</View>
			)}
		</View>
	);
}

// packages/help/src/components/FeatureCard.svelte
<script lang="ts">
	import type { FeatureItem } from '../content';

	interface Props {
		item: FeatureItem;
		learnMoreLabel?: string;
		comingSoonLabel?: string;
	}

	let { item, learnMoreLabel = 'Learn more', comingSoonLabel = 'Coming soon' }: Props = $props();
</script>

<div
	class="relative rounded-lg border border-gray-200 bg-white p-5 transition-shadow hover:shadow-md dark:border-gray-700 dark:bg-gray-800"
>
	{#if item.comingSoon}
		<span
			class="absolute right-3 top-3 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700 dark:bg-amber-900/30 dark:text-amber-400"
		>
			{comingSoonLabel}
		</span>
	{/if}

	<div class="mb-3 flex items-center gap-3">
		{#if item.icon}
			<span class="text-2xl">{item.icon}</span>
		{/if}
		<h3 class="font-semibold text-gray-900 dark:text-gray-100">
			{item.title}
		</h3>
	</div>

	<p class="mb-3 text-sm text-gray-600 dark:text-gray-400">
		{item.description}
	</p>

	{#if item.highlights && item.highlights.length > 0}
		<ul class="mb-3 space-y-1">
			{#each item.highlights as highlight}
				<li class="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
					<svg
						class="text-primary-500 mt-0.5 h-4 w-4 flex-shrink-0"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M5 13l4 4L19 7"
						/>
					</svg>
					{highlight}
				</li>
			{/each}
		</ul>
	{/if}

	{#if item.learnMoreUrl}
		<a
			href={item.learnMoreUrl}
			class="text-primary-600 dark:text-primary-400 text-sm font-medium hover:underline"
		>
			{learnMoreLabel} →
		</a>
	{/if}
</div>
