// apps/figgos/apps/mobile/app/(tabs)/collection.tsx
import { useState, useCallback } from 'react';
import {
	View,
	Text,
	Image,
	Pressable,
	FlatList,
	Dimensions,
	ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useFocusEffect } from 'expo-router';
import type { FigureResponse } from '@figgos/shared';
import { api } from '../../services/api';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const GAP = 10;
const PADDING = 14;
const COLUMNS = 2;
const CARD_WIDTH = (SCREEN_WIDTH - PADDING * 2 - GAP * (COLUMNS - 1)) / COLUMNS;
const CARD_HEIGHT = CARD_WIDTH * 1.45;

function CardThumbnail({ figure }: { figure: FigureResponse }) {
	const router = useRouter();

	return (
		<Pressable
			onPress={() => router.push(`/card/v2/${figure.id}` as any)}
			style={{ width: CARD_WIDTH }}
			className="active:opacity-80"
		>
			<View
				style={{
					width: CARD_WIDTH,
					height: CARD_HEIGHT,
					borderRadius: 12,
					overflow: 'hidden',
				}}
			>
				{figure.imageUrl ? (
					<Image
						source={{ uri: figure.imageUrl }}
						style={{ width: '100%', height: '100%' }}
						resizeMode="cover"
					/>
				) : (
					<View
						className="bg-surface items-center justify-center"
						style={{
							width: '100%',
							height: '100%',
							borderWidth: 2,
							borderColor: 'rgb(50, 50, 80)',
							borderRadius: 12,
						}}
					>
						<Text className="text-muted-foreground" style={{ fontSize: 11 }}>
							{figure.name}
						</Text>
					</View>
				)}
			</View>
		</Pressable>
	);
}

export default function CollectionScreen() {
	const [figures, setFigures] = useState<FigureResponse[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);

	useFocusEffect(
		useCallback(() => {
			setLoading(true);
			api.figures
				.list()
				.then(({ figures }) => {
					setFigures(figures);
					setError(null);
				})
				.catch((e) => setError(e.message))
				.finally(() => setLoading(false));
		}, [])
	);

	return (
		<SafeAreaView className="flex-1 bg-background" edges={['top']}>
			<View style={{ paddingHorizontal: PADDING, paddingTop: 24, paddingBottom: 16 }}>
				<Text
					className="text-foreground"
					style={{ fontSize: 28, fontWeight: '900', letterSpacing: -0.5 }}
				>
					Collection
				</Text>
				<Text className="text-muted-foreground" style={{ fontSize: 13, marginTop: 2 }}>
					{loading ? '...' : `${figures.length} ${figures.length === 1 ? 'Figgo' : 'Figgos'}`}
				</Text>
			</View>

			{loading ? (
				<View className="flex-1 items-center justify-center">
					<ActivityIndicator color="rgb(255, 204, 0)" size="large" />
				</View>
			) : error ? (
				<View className="flex-1 items-center justify-center px-6">
					<Text className="text-destructive text-center" style={{ fontSize: 14 }}>
						{error}
					</Text>
				</View>
			) : figures.length === 0 ? (
				<View className="flex-1 items-center justify-center px-6">
					<Text
						className="text-muted-foreground text-center"
						style={{ fontSize: 16, fontWeight: '700' }}
					>
						No figures yet
					</Text>
					<Text className="text-muted-foreground text-center mt-2" style={{ fontSize: 13 }}>
						Create your first Figgo!
					</Text>
				</View>
			) : (
				<FlatList
					data={figures}
					numColumns={COLUMNS}
					keyExtractor={(item) => item.id}
					contentContainerStyle={{ paddingHorizontal: PADDING, paddingBottom: 40 }}
					columnWrapperStyle={{ gap: GAP, marginBottom: GAP }}
					renderItem={({ item }) => <CardThumbnail figure={item} />}
				/>
			)}
		</SafeAreaView>
	);
}

// apps/figgos/apps/web/src/routes/collection/+page.svelte
<script lang="ts">
	import type { FigureResponse } from '@figgos/shared';
	import { api } from '$lib/api';

	let figures = $state<FigureResponse[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);

	$effect(() => {
		api.figures
			.list()
			.then(({ figures: f }) => {
				figures = f;
				error = null;
			})
			.catch((e) => (error = e.message))
			.finally(() => (loading = false));
	});
</script>

<div class="mx-auto max-w-2xl px-5 pt-8">
	<h1 class="text-4xl font-black tracking-tight text-foreground">Collection</h1>
	<p class="mt-1 text-base text-muted-foreground">
		{loading ? '...' : `${figures.length} ${figures.length === 1 ? 'Figgo' : 'Figgos'}`}
	</p>

	{#if loading}
		<div class="mt-20 flex justify-center">
			<svg class="h-8 w-8 animate-spin text-primary" viewBox="0 0 24 24" fill="none">
				<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"
				></circle>
				<path
					class="opacity-75"
					fill="currentColor"
					d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
				></path>
			</svg>
		</div>
	{:else if error}
		<div class="mt-20 text-center">
			<p class="text-base text-destructive">{error}</p>
		</div>
	{:else if figures.length === 0}
		<div class="mt-20 text-center">
			<p class="text-lg font-bold text-muted-foreground">No figures yet</p>
			<p class="mt-2 text-sm text-muted-foreground">Create your first Figgo!</p>
		</div>
	{:else}
		<div class="mt-6 grid grid-cols-2 gap-4">
			{#each figures as figure (figure.id)}
				<a
					href="/card/{figure.id}"
					class="block transition-opacity hover:opacity-80 active:opacity-70"
				>
					<div class="aspect-[1/1.45] overflow-hidden rounded-xl">
						{#if figure.imageUrl}
							<img src={figure.imageUrl} alt={figure.name} class="h-full w-full object-cover" />
						{:else}
							<div
								class="flex h-full w-full items-center justify-center rounded-xl border-2 border-border-muted bg-surface"
							>
								<span class="text-sm font-bold text-muted-foreground">{figure.name}</span>
							</div>
						{/if}
					</div>
				</a>
			{/each}
		</div>
	{/if}
</div>
