// apps/nutriphi/apps/web/src/lib/components/meals/NutritionBar.svelte
<script lang="ts">
	import type { Meal } from '$lib/types/meal';

	interface Props {
		meal: Meal;
		showDetailed?: boolean;
	}

	let { meal, showDetailed = false }: Props = $props();

	const healthColor = $derived(() => {
		if (!meal.health_score) return 'bg-gray-400';
		if (meal.health_score >= 8) return 'bg-green-500';
		if (meal.health_score >= 6) return 'bg-yellow-500';
		if (meal.health_score >= 4) return 'bg-orange-500';
		return 'bg-red-500';
	});

	const healthLabel = $derived(() => {
		if (!meal.health_category) return '';
		const labels: Record<string, string> = {
			very_healthy: 'Sehr gesund',
			healthy: 'Gesund',
			moderate: 'Moderat',
			unhealthy: 'Ungesund',
		};
		return labels[meal.health_category] || '';
	});
</script>

<div class="space-y-4">
	<!-- Calories Header -->
	<div class="flex items-center justify-between">
		<div>
			<p class="text-3xl font-bold text-gray-900 dark:text-white">
				{meal.total_calories ? Math.round(meal.total_calories) : '—'} kcal
			</p>
			{#if healthLabel()}
				<p class="text-sm text-gray-600 dark:text-gray-400">{healthLabel()}</p>
			{/if}
		</div>
		{#if meal.health_score}
			<div class="flex items-center gap-2">
				<div class="h-4 w-4 rounded-full {healthColor()}"></div>
				<span class="text-xl font-semibold text-gray-900 dark:text-white">
					{meal.health_score}/10
				</span>
			</div>
		{/if}
	</div>

	<!-- Macro Pills -->
	<div class="grid grid-cols-3 gap-3">
		<div class="rounded-xl bg-blue-50 p-3 text-center dark:bg-blue-900/20">
			<p class="text-2xl font-bold text-blue-600 dark:text-blue-400">
				{meal.total_protein ? Math.round(meal.total_protein) : '—'}g
			</p>
			<p class="text-xs text-gray-600 dark:text-gray-400">Protein</p>
		</div>
		<div class="rounded-xl bg-green-50 p-3 text-center dark:bg-green-900/20">
			<p class="text-2xl font-bold text-green-600 dark:text-green-400">
				{meal.total_carbs ? Math.round(meal.total_carbs) : '—'}g
			</p>
			<p class="text-xs text-gray-600 dark:text-gray-400">Carbs</p>
		</div>
		<div class="rounded-xl bg-orange-50 p-3 text-center dark:bg-orange-900/20">
			<p class="text-2xl font-bold text-orange-600 dark:text-orange-400">
				{meal.total_fat ? Math.round(meal.total_fat) : '—'}g
			</p>
			<p class="text-xs text-gray-600 dark:text-gray-400">Fett</p>
		</div>
	</div>

	<!-- Detailed Progress Bars -->
	{#if showDetailed}
		<div class="space-y-3 pt-2">
			<!-- Protein -->
			<div>
				<div class="mb-1 flex justify-between text-sm">
					<span class="text-gray-600 dark:text-gray-400">Protein</span>
					<span class="font-medium text-blue-600 dark:text-blue-400">
						{meal.total_protein ? Math.round(meal.total_protein) : 0}g
					</span>
				</div>
				<div class="h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
					<div
						class="h-full bg-blue-500 transition-all"
						style="width: {Math.min(((meal.total_protein || 0) / 50) * 100, 100)}%"
					></div>
				</div>
			</div>

			<!-- Carbs -->
			<div>
				<div class="mb-1 flex justify-between text-sm">
					<span class="text-gray-600 dark:text-gray-400">Kohlenhydrate</span>
					<span class="font-medium text-green-600 dark:text-green-400">
						{meal.total_carbs ? Math.round(meal.total_carbs) : 0}g
					</span>
				</div>
				<div class="h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
					<div
						class="h-full bg-green-500 transition-all"
						style="width: {Math.min(((meal.total_carbs || 0) / 100) * 100, 100)}%"
					></div>
				</div>
			</div>

			<!-- Fat -->
			<div>
				<div class="mb-1 flex justify-between text-sm">
					<span class="text-gray-600 dark:text-gray-400">Fett</span>
					<span class="font-medium text-orange-600 dark:text-orange-400">
						{meal.total_fat ? Math.round(meal.total_fat) : 0}g
					</span>
				</div>
				<div class="h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
					<div
						class="h-full bg-orange-500 transition-all"
						style="width: {Math.min(((meal.total_fat || 0) / 65) * 100, 100)}%"
					></div>
				</div>
			</div>

			<!-- Fiber -->
			{#if meal.total_fiber !== undefined}
				<div>
					<div class="mb-1 flex justify-between text-sm">
						<span class="text-gray-600 dark:text-gray-400">Ballaststoffe</span>
						<span class="font-medium text-purple-600 dark:text-purple-400">
							{Math.round(meal.total_fiber)}g
						</span>
					</div>
					<div class="h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
						<div
							class="h-full bg-purple-500 transition-all"
							style="width: {Math.min((meal.total_fiber / 25) * 100, 100)}%"
						></div>
					</div>
				</div>
			{/if}

			<!-- Sugar -->
			{#if meal.total_sugar !== undefined}
				<div>
					<div class="mb-1 flex justify-between text-sm">
						<span class="text-gray-600 dark:text-gray-400">Zucker</span>
						<span class="font-medium text-pink-600 dark:text-pink-400">
							{Math.round(meal.total_sugar)}g
						</span>
					</div>
					<div class="h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700">
						<div
							class="h-full bg-pink-500 transition-all"
							style="width: {Math.min((meal.total_sugar / 50) * 100, 100)}%"
						></div>
					</div>
				</div>
			{/if}
		</div>
	{/if}
</div>

// apps/nutriphi/apps/mobile/components/meals/NutritionBar.tsx
import React from 'react';
import { View, Text } from 'react-native';
import { Meal } from '@/types/Database';

interface NutritionBarProps {
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  healthScore?: number;
  compact?: boolean;
  meal?: Meal;
  showDetailed?: boolean;
}

export const NutritionBar: React.FC<NutritionBarProps> = ({
  calories,
  protein,
  carbs,
  fat,
  healthScore,
  compact = false,
  meal,
  showDetailed = false,
}) => {
  // Use meal data if provided, otherwise use individual props
  const mealCalories = meal?.total_calories || calories;
  const mealProtein = meal?.total_protein || protein;
  const mealCarbs = meal?.total_carbs || carbs;
  const mealFat = meal?.total_fat || fat;
  const mealHealthScore = meal?.health_score || healthScore;
  const mealFiber = meal?.total_fiber;
  const mealSugar = meal?.total_sugar;
  const formatValue = (value?: number, unit: string = 'g') => {
    if (value === undefined || value === null) return '--';
    return `${Math.round(value)}${unit}`;
  };

  const getHealthScoreColor = (score?: number) => {
    if (!score) return 'bg-gray-300';
    if (score >= 8) return 'bg-green-500';
    if (score >= 6) return 'bg-yellow-500';
    if (score >= 4) return 'bg-orange-500';
    return 'bg-red-500';
  };

  const getHealthScoreText = (score?: number) => {
    if (!score) return 'Not analyzed';
    if (score >= 8) return 'Very Healthy';
    if (score >= 6) return 'Healthy';
    if (score >= 4) return 'Moderate';
    return 'Unhealthy';
  };

  if (compact) {
    return (
      <View className="flex-row items-center space-x-4">
        <View className="flex-row items-center space-x-1">
          <Text className="text-lg font-bold text-gray-900">
            {formatValue(mealCalories, ' kcal')}
          </Text>
        </View>
        {mealHealthScore && (
          <View className="flex-row items-center space-x-2">
            <View className={`h-3 w-3 rounded-full ${getHealthScoreColor(mealHealthScore)}`} />
            <Text className="text-sm text-gray-600">{mealHealthScore.toFixed(1)}/10</Text>
          </View>
        )}
      </View>
    );
  }

  return (
    <View className="space-y-3">
      {/* Calories Header */}
      <View className="flex-row items-center justify-between">
        <Text className="text-2xl font-bold text-gray-900">
          {formatValue(mealCalories, ' kcal')}
        </Text>
        {mealHealthScore && (
          <View className="flex-row items-center space-x-2">
            <View className={`h-4 w-4 rounded-full ${getHealthScoreColor(mealHealthScore)}`} />
            <View className="items-end">
              <Text className="text-sm font-medium text-gray-900">
                {mealHealthScore.toFixed(1)}/10
              </Text>
              <Text className="text-xs text-gray-500">{getHealthScoreText(mealHealthScore)}</Text>
            </View>
          </View>
        )}
      </View>

      {/* Macronutrients */}
      <View className="flex-row justify-between">
        <View className="items-center">
          <Text className="text-lg font-semibold text-blue-600">{formatValue(mealProtein)}</Text>
          <Text className="text-xs uppercase tracking-wide text-gray-500">Protein</Text>
        </View>

        <View className="items-center">
          <Text className="text-lg font-semibold text-green-600">{formatValue(mealCarbs)}</Text>
          <Text className="text-xs uppercase tracking-wide text-gray-500">Carbs</Text>
        </View>

        <View className="items-center">
          <Text className="text-lg font-semibold text-orange-600">{formatValue(mealFat)}</Text>
          <Text className="text-xs uppercase tracking-wide text-gray-500">Fat</Text>
        </View>
      </View>

      {/* Additional nutrients for detailed view */}
      {showDetailed && (mealFiber || mealSugar) && (
        <View className="flex-row justify-between">
          {mealFiber && (
            <View className="items-center">
              <Text className="text-lg font-semibold text-purple-600">
                {formatValue(mealFiber)}
              </Text>
              <Text className="text-xs uppercase tracking-wide text-gray-500">Fiber</Text>
            </View>
          )}
          {mealSugar && (
            <View className="items-center">
              <Text className="text-lg font-semibold text-pink-600">{formatValue(mealSugar)}</Text>
              <Text className="text-xs uppercase tracking-wide text-gray-500">Sugar</Text>
            </View>
          )}
          <View className="items-center">
            <Text className="text-lg font-semibold text-transparent">--</Text>
            <Text className="text-xs uppercase tracking-wide text-transparent">--</Text>
          </View>
        </View>
      )}

      {/* Visual Progress Bars */}
      <View className="space-y-2">
        <View className="flex-row items-center space-x-3">
          <Text className="w-12 text-xs text-gray-500">PROT</Text>
          <View className="h-2 flex-1 rounded-full bg-gray-200">
            <View
              className="h-2 rounded-full bg-blue-500"
              style={{ width: `${Math.min(((mealProtein || 0) / 50) * 100, 100)}%` }}
            />
          </View>
          <Text className="w-8 text-xs text-gray-500">{formatValue(mealProtein)}</Text>
        </View>

        <View className="flex-row items-center space-x-3">
          <Text className="w-12 text-xs text-gray-500">CARB</Text>
          <View className="h-2 flex-1 rounded-full bg-gray-200">
            <View
              className="h-2 rounded-full bg-green-500"
              style={{ width: `${Math.min(((mealCarbs || 0) / 100) * 100, 100)}%` }}
            />
          </View>
          <Text className="w-8 text-xs text-gray-500">{formatValue(mealCarbs)}</Text>
        </View>

        <View className="flex-row items-center space-x-3">
          <Text className="w-12 text-xs text-gray-500">FAT</Text>
          <View className="h-2 flex-1 rounded-full bg-gray-200">
            <View
              className="h-2 rounded-full bg-orange-500"
              style={{ width: `${Math.min(((mealFat || 0) / 30) * 100, 100)}%` }}
            />
          </View>
          <Text className="w-8 text-xs text-gray-500">{formatValue(mealFat)}</Text>
        </View>

        {/* Additional progress bars for detailed view */}
        {showDetailed && mealFiber && (
          <View className="flex-row items-center space-x-3">
            <Text className="w-12 text-xs text-gray-500">FIBER</Text>
            <View className="h-2 flex-1 rounded-full bg-gray-200">
              <View
                className="h-2 rounded-full bg-purple-500"
                style={{ width: `${Math.min(((mealFiber || 0) / 25) * 100, 100)}%` }}
              />
            </View>
            <Text className="w-8 text-xs text-gray-500">{formatValue(mealFiber)}</Text>
          </View>
        )}

        {showDetailed && mealSugar && (
          <View className="flex-row items-center space-x-3">
            <Text className="w-12 text-xs text-gray-500">SUGAR</Text>
            <View className="h-2 flex-1 rounded-full bg-gray-200">
              <View
                className="h-2 rounded-full bg-pink-500"
                style={{ width: `${Math.min(((mealSugar || 0) / 50) * 100, 100)}%` }}
              />
            </View>
            <Text className="w-8 text-xs text-gray-500">{formatValue(mealSugar)}</Text>
          </View>
        )}
      </View>
    </View>
  );
};
