// apps/memoro/apps/web-archived/src/lib/components/atoms/Text.svelte
<script lang="ts">
	type TextVariant = 'body' | 'body-secondary' | 'small' | 'large' | 'muted';
	type TextAlign = 'left' | 'center' | 'right';
	type TextWeight = 'normal' | 'medium' | 'semibold' | 'bold';

	interface Props {
		variant?: TextVariant;
		align?: TextAlign;
		weight?: TextWeight;
		class?: string;
		children?: any;
	}

	let {
		variant = 'body',
		align = 'left',
		weight = 'normal',
		class: className = '',
		children,
	}: Props = $props();

	const variantClasses: Record<TextVariant, string> = {
		body: 'text-base text-theme leading-relaxed',
		'body-secondary': 'text-base text-theme-secondary leading-relaxed',
		small: 'text-sm text-theme',
		large: 'text-lg text-theme leading-relaxed',
		muted: 'text-sm text-theme-muted',
	};

	const alignClasses: Record<TextAlign, string> = {
		left: 'text-left',
		center: 'text-center',
		right: 'text-right',
	};

	const weightClasses: Record<TextWeight, string> = {
		normal: 'font-normal',
		medium: 'font-medium',
		semibold: 'font-semibold',
		bold: 'font-bold',
	};

	const classes = $derived(
		`${variantClasses[variant]} ${alignClasses[align]} ${weightClasses[weight]} ${className}`
	);
</script>

<p class={classes}>
	{@render children?.()}
</p>

// manadeck/apps/mobile/components/ui/Text.tsx
import React from 'react';
import { Text as RNText, TextProps as RNTextProps } from 'react-native';

type TextVariant = 'h1' | 'h2' | 'h3' | 'h4' | 'body' | 'caption' | 'small';

interface TextProps extends RNTextProps {
  variant?: TextVariant;
  className?: string;
}

const getVariantClasses = (variant: TextVariant): string => {
  switch (variant) {
    case 'h1':
      return 'text-4xl font-bold';
    case 'h2':
      return 'text-3xl font-bold';
    case 'h3':
      return 'text-2xl font-semibold';
    case 'h4':
      return 'text-xl font-semibold';
    case 'body':
      return 'text-base';
    case 'caption':
      return 'text-sm';
    case 'small':
      return 'text-xs';
    default:
      return 'text-base';
  }
};

export const Text: React.FC<TextProps> = ({
  variant = 'body',
  className = '',
  children,
  ...props
}) => {
  const variantClasses = getVariantClasses(variant);
  const combinedClassName = `${variantClasses} ${className}`.trim();

  return (
    <RNText className={combinedClassName} {...props}>
      {children}
    </RNText>
  );
};
