// apps-archived/nutriphi/apps/mobile/components/meals/FoodItemList.tsx
import React from 'react';
import { View, Text, ScrollView } from 'react-native';
import { FoodItem } from '@/types/Database';
import { FoodItemCard } from './FoodItemCard';

interface FoodItemListProps {
	foodItems: FoodItem[];
	title?: string;
	showTitle?: boolean;
}

export const FoodItemList: React.FC<FoodItemListProps> = ({
	foodItems,
	title = 'Erkannte Lebensmittel',
	showTitle = true,
}) => {
	if (!foodItems || foodItems.length === 0) {
		return (
			<View className="py-4">
				{showTitle && <Text className="mb-3 text-lg font-semibold text-gray-900">{title}</Text>}
				<View className="items-center rounded-lg bg-gray-50 p-6">
					<Text className="mb-2 text-4xl">🍽️</Text>
					<Text className="text-center text-gray-600">Keine Lebensmittel erkannt</Text>
				</View>
			</View>
		);
	}

	const getCategoryIcon = (category: string) => {
		switch (category) {
			case 'protein':
				return '🥩';
			case 'vegetable':
				return '🥕';
			case 'grain':
				return '🌾';
			case 'fruit':
				return '🍎';
			case 'dairy':
				return '🥛';
			case 'fat':
				return '🥑';
			case 'processed':
				return '📦';
			case 'beverage':
				return '🥤';
			default:
				return '🍽️';
		}
	};

	const getCategoryColor = (category: string) => {
		switch (category) {
			case 'protein':
				return 'border-red-200 bg-red-50';
			case 'vegetable':
				return 'border-green-200 bg-green-50';
			case 'grain':
				return 'border-yellow-200 bg-yellow-50';
			case 'fruit':
				return 'border-orange-200 bg-orange-50';
			case 'dairy':
				return 'border-blue-200 bg-blue-50';
			case 'fat':
				return 'border-purple-200 bg-purple-50';
			case 'processed':
				return 'border-gray-200 bg-gray-50';
			case 'beverage':
				return 'border-cyan-200 bg-cyan-50';
			default:
				return 'border-gray-200 bg-gray-50';
		}
	};

	// Group food items by category
	const groupedByCategory = foodItems.reduce(
		(acc, item) => {
			const category = item.category || 'other';
			if (!acc[category]) {
				acc[category] = [];
			}
			acc[category].push(item);
			return acc;
		},
		{} as Record<string, FoodItem[]>
	);

	const categoryOrder = [
		'protein',
		'vegetable',
		'grain',
		'fruit',
		'dairy',
		'fat',
		'beverage',
		'processed',
		'other',
	];
	const sortedCategories = categoryOrder.filter((category) => groupedByCategory[category]);
	const otherCategories = Object.keys(groupedByCategory).filter(
		(category) => !categoryOrder.includes(category)
	);
	const allCategories = [...sortedCategories, ...otherCategories];

	const getCategoryName = (category: string) => {
		switch (category) {
			case 'protein':
				return 'Proteine';
			case 'vegetable':
				return 'Gemüse';
			case 'grain':
				return 'Getreide';
			case 'fruit':
				return 'Obst';
			case 'dairy':
				return 'Milchprodukte';
			case 'fat':
				return 'Fette';
			case 'processed':
				return 'Verarbeitete Lebensmittel';
			case 'beverage':
				return 'Getränke';
			default:
				return 'Sonstige';
		}
	};

	return (
		<View className="py-4">
			{showTitle && (
				<Text className="mb-4 text-lg font-semibold text-gray-900">
					{title} ({foodItems.length})
				</Text>
			)}

			<ScrollView showsVerticalScrollIndicator={false}>
				{allCategories.map((category) => (
					<View key={category} className="mb-6">
						{/* Category Header */}
						<View className="mb-3 flex-row items-center">
							<Text className="mr-2 text-2xl">{getCategoryIcon(category)}</Text>
							<Text className="text-base font-medium text-gray-800">
								{getCategoryName(category)} ({groupedByCategory[category].length})
							</Text>
						</View>

						{/* Category Items */}
						<View className="space-y-2">
							{groupedByCategory[category].map((item, index) => (
								<FoodItemCard
									key={item.id || `${category}-${index}`}
									foodItem={item}
									categoryColor={getCategoryColor(category)}
								/>
							))}
						</View>
					</View>
				))}
			</ScrollView>
		</View>
	);
};

// apps-archived/nutriphi/apps/web/src/lib/components/meals/FoodItemList.svelte
<script lang="ts">
	import type { FoodItem } from '$lib/types/meal';

	interface Props {
		items: FoodItem[];
	}

	let { items }: Props = $props();

	function getCategoryLabel(category: string): string {
		const labels: Record<string, string> = {
			protein: 'Protein',
			vegetable: 'Gemüse',
			grain: 'Getreide',
			fruit: 'Obst',
			dairy: 'Milchprodukt',
			fat: 'Fett',
			processed: 'Verarbeitet',
			beverage: 'Getränk',
		};
		return labels[category] || category;
	}

	function getCategoryColor(category: string): string {
		const colors: Record<string, string> = {
			protein: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
			vegetable: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
			grain: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
			fruit: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
			dairy: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
			fat: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
			processed: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300',
			beverage: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-400',
		};
		return colors[category] || 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300';
	}
</script>

{#if items.length === 0}
	<p class="text-center text-gray-500 dark:text-gray-400">Keine Zutaten erkannt</p>
{:else}
	<div class="space-y-2">
		{#each items as item (item.id)}
			<div class="flex items-center justify-between rounded-xl bg-gray-50 p-3 dark:bg-gray-700/50">
				<div class="flex items-center gap-3">
					<span class="rounded-lg px-2 py-1 text-xs font-medium {getCategoryColor(item.category)}">
						{getCategoryLabel(item.category)}
					</span>
					<div>
						<p class="font-medium text-gray-900 dark:text-white">{item.name}</p>
						<p class="text-sm text-gray-600 dark:text-gray-400">{item.portion_size}</p>
					</div>
				</div>
				<div class="text-right">
					{#if item.calories}
						<p class="font-semibold text-gray-900 dark:text-white">
							{Math.round(item.calories)} kcal
						</p>
					{/if}
					{#if item.confidence}
						<p class="text-xs text-gray-500">{Math.round(item.confidence * 100)}%</p>
					{/if}
				</div>
			</div>
		{/each}
	</div>
{/if}
