// packages/shared-help-ui/src/components/FAQItem.svelte
<script lang="ts">
	import type { FAQItem } from '@manacore/shared-help-types';

	interface Props {
		item: FAQItem;
		expanded?: boolean;
		onToggle?: () => void;
	}

	let { item, expanded = false, onToggle }: Props = $props();

	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			onToggle?.();
		}
	}
</script>

<div class="border-b border-gray-200 dark:border-gray-700">
	<button
		type="button"
		class="flex w-full items-center justify-between py-4 text-left transition-colors hover:bg-gray-50 dark:hover:bg-gray-800/50"
		aria-expanded={expanded}
		onclick={onToggle}
		onkeydown={handleKeyDown}
	>
		<span class="pr-4 font-medium text-gray-900 dark:text-gray-100">
			{item.question}
		</span>
		<span
			class="flex-shrink-0 text-gray-500 transition-transform duration-200 dark:text-gray-400"
			class:rotate-180={expanded}
		>
			<svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
			</svg>
		</span>
	</button>

	{#if expanded}
		<div class="prose prose-sm dark:prose-invert max-w-none pb-4 text-gray-600 dark:text-gray-300">
			{@html item.answer}
		</div>
	{/if}
</div>

// packages/shared-help-mobile/src/components/FAQItem.tsx
/**
 * Expandable FAQ Item component for mobile
 */

import React from 'react';
import { View, Text, TouchableOpacity, LayoutAnimation, Platform, UIManager } from 'react-native';
import type { FAQItem as FAQItemType } from '@manacore/shared-help-types';

// Enable LayoutAnimation on Android
if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) {
	UIManager.setLayoutAnimationEnabledExperimental(true);
}

interface FAQItemProps {
	item: FAQItemType;
	expanded?: boolean;
	onToggle?: () => void;
}

export function FAQItem({ item, expanded = false, onToggle }: FAQItemProps) {
	function handlePress() {
		LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
		onToggle?.();
	}

	// Strip HTML tags for mobile display
	const plainAnswer = item.answer.replace(/<[^>]*>/g, '').trim();

	return (
		<View className="border-b border-gray-200 dark:border-gray-700">
			<TouchableOpacity
				onPress={handlePress}
				className="py-4 flex-row items-center justify-between"
				accessibilityRole="button"
				accessibilityState={{ expanded }}
			>
				<Text className="flex-1 pr-4 font-medium text-gray-900 dark:text-gray-100 text-base">
					{item.question}
				</Text>
				<Text
					className="text-gray-500 dark:text-gray-400"
					style={{ transform: [{ rotate: expanded ? '180deg' : '0deg' }] }}
				>
					▼
				</Text>
			</TouchableOpacity>

			{expanded && (
				<View className="pb-4">
					<Text className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed">
						{plainAnswer}
					</Text>
				</View>
			)}
		</View>
	);
}
