// apps/context/apps/mobile/components/ui/Badge.tsx
import { View, ViewProps } from 'react-native';
import { Text } from './Text';

type BadgeVariant = 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info';

type BadgeProps = {
	label: string;
	variant?: BadgeVariant;
} & ViewProps;

export const Badge = ({ label, variant = 'default', className, ...props }: BadgeProps) => {
	const variantStyles = {
		default: 'bg-gray-100 dark:bg-gray-700',
		primary: 'bg-indigo-100 dark:bg-indigo-900',
		success: 'bg-green-100 dark:bg-green-900',
		warning: 'bg-yellow-100 dark:bg-yellow-900',
		danger: 'bg-red-100 dark:bg-red-900',
		info: 'bg-blue-100 dark:bg-blue-900',
	};

	const textStyles = {
		default: 'text-gray-800 dark:text-gray-200',
		primary: 'text-indigo-800 dark:text-indigo-200',
		success: 'text-green-800 dark:text-green-200',
		warning: 'text-yellow-800 dark:text-yellow-200',
		danger: 'text-red-800 dark:text-red-200',
		info: 'text-blue-800 dark:text-blue-200',
	};

	return (
		<View
			className={`px-2 py-1 rounded-full ${variantStyles[variant]} ${className || ''}`}
			{...props}
		>
			<Text className={`text-xs font-medium ${textStyles[variant]}`}>{label}</Text>
		</View>
	);
};

// packages/shared-ui/src/atoms/Badge.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	type BadgeVariant = 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info';
	type BadgeSize = 'sm' | 'md';

	interface Props {
		variant?: BadgeVariant;
		size?: BadgeSize;
		class?: string;
		children?: Snippet;
	}

	let { variant = 'default', size = 'md', class: className = '', children }: Props = $props();

	const variantClasses: Record<BadgeVariant, string> = {
		default: 'bg-menu text-theme border-theme',
		primary: 'bg-primary/20 text-primary border-primary/30',
		success: 'bg-green-500/20 text-green-600 dark:text-green-400 border-green-500/30',
		warning: 'bg-yellow-500/20 text-yellow-600 dark:text-yellow-400 border-yellow-500/30',
		danger: 'bg-red-500/20 text-red-600 dark:text-red-400 border-red-500/30',
		info: 'bg-blue-500/20 text-blue-600 dark:text-blue-400 border-blue-500/30',
	};

	const sizeClasses: Record<BadgeSize, string> = {
		sm: 'px-1.5 py-0.5 text-xs',
		md: 'px-2 py-1 text-sm',
	};

	const classes = $derived(
		`inline-flex items-center rounded-full border font-medium ${variantClasses[variant]} ${sizeClasses[size]} ${className}`
	);
</script>

<span class={classes}>
	{@render children?.()}
</span>
