// manacore/apps/web/src/lib/components/ui/Input.svelte
<script lang="ts">
	interface Props {
		type?: string;
		name?: string;
		id?: string;
		placeholder?: string;
		value?: string;
		required?: boolean;
		disabled?: boolean;
		class?: string;
		autocomplete?: 'email' | 'current-password' | 'new-password' | 'username' | 'off' | string;
		oninput?: (event: Event) => void;
	}

	let {
		type = 'text',
		name,
		id,
		placeholder,
		value = $bindable(''),
		required = false,
		disabled = false,
		class: className = '',
		autocomplete,
		oninput
	}: Props = $props();
</script>

<input
	{type}
	{name}
	{id}
	{placeholder}
	{required}
	{disabled}
	autocomplete={autocomplete as any}
	bind:value
	oninput={oninput}
	class="block w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-gray-900 placeholder-gray-500 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-100 dark:placeholder-gray-400 {className}"
/>

// apps/maerchenzauber/apps/landing/src/components/ui/Input.tsx
import React, { useState } from 'react';

interface InputProps {
  type?: 'text' | 'email' | 'password' | 'number' | 'tel';
  placeholder?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onFocus?: () => void;
  onBlur?: () => void;
  disabled?: boolean;
  required?: boolean;
  className?: string;
  icon?: React.ReactNode;
}

export default function Input({
  type = 'text',
  placeholder,
  value,
  onChange,
  onFocus,
  onBlur,
  disabled = false,
  required = false,
  className = '',
  icon
}: InputProps) {
  const [isFocused, setIsFocused] = useState(false);

  const handleFocus = () => {
    setIsFocused(true);
    onFocus?.();
  };

  const handleBlur = () => {
    setIsFocused(false);
    onBlur?.();
  };

  return (
    <div className="relative">
      {icon && (
        <div className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary">
          {icon}
        </div>
      )}
      <input
        type={type}
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        disabled={disabled}
        required={required}
        className={`
          w-full bg-bg-input rounded-lg text-text-primary 
          px-3 py-3 text-base border-none outline-none
          placeholder:text-text-muted
          focus:ring-2 focus:ring-yellow-dark
          disabled:opacity-50 disabled:cursor-not-allowed
          transition-all duration-200
          ${icon ? 'pl-10' : ''}
          ${className}
        `}
      />
    </div>
  );
}
