// packages/shared-subscription-ui/src/BillingToggle.svelte
<script lang="ts">
	import type { BillingCycle } from '@manacore/shared-subscription-types';

	interface Props {
		billingCycle: BillingCycle;
		onChange: (cycle: BillingCycle) => void;
		yearlyDiscount?: string;
		monthlyLabel?: string;
		yearlyLabel?: string;
	}

	let {
		billingCycle,
		onChange,
		yearlyDiscount = '33%',
		monthlyLabel = 'Monatlich',
		yearlyLabel = 'Jährlich'
	}: Props = $props();
</script>

<div class="mx-auto mb-2 flex max-w-lg rounded-lg p-1 bg-menu">
	<button
		onclick={() => onChange('monthly')}
		class="flex flex-1 items-center justify-center rounded-md py-3 transition-colors"
		class:bg-content={billingCycle === 'monthly'}
		class:text-mana={billingCycle === 'monthly'}
		class:font-bold={billingCycle === 'monthly'}
		class:text-theme={billingCycle !== 'monthly'}
	>
		<span class="text-sm">
			{monthlyLabel}
		</span>
	</button>

	<button
		onclick={() => onChange('yearly')}
		class="flex flex-1 items-center justify-center gap-2 rounded-md py-3 transition-colors"
		class:bg-content={billingCycle === 'yearly'}
		class:text-mana={billingCycle === 'yearly'}
		class:font-bold={billingCycle === 'yearly'}
		class:text-theme={billingCycle !== 'yearly'}
	>
		<span class="text-sm">
			{yearlyLabel}
		</span>
		{#if yearlyDiscount}
			<span class="rounded-xl bg-mana px-2 py-1 text-xs font-bold text-white">
				-{yearlyDiscount}
			</span>
		{/if}
	</button>
</div>

// games/figgos/apps/mobile/components/subscription/BillingToggle.tsx
import React from 'react';
import { View, Text, Pressable } from 'react-native';
import { useTheme } from '../../utils/ThemeContext';
import SubscriptionButton from './SubscriptionButton';

export type BillingCycle = 'monthly' | 'yearly';

interface BillingToggleProps {
	billingCycle: BillingCycle;
	onChange: (cycle: BillingCycle) => void;
	yearlyDiscount?: string;
}

export const BillingToggle: React.FC<BillingToggleProps> = ({
	billingCycle,
	onChange,
	yearlyDiscount = '50%',
}) => {
	const { theme } = useTheme();

	return (
		<View className="flex-row bg-[rgba(255,255,255,0.05)] rounded-lg mb-6 p-1 md:max-w-md md:mx-auto">
			<Pressable
				className={`flex-1 py-3 items-center rounded-md flex-row justify-center ${billingCycle === 'monthly' ? 'bg-[rgba(255,255,255,0.1)]' : ''}`}
				onPress={() => onChange('monthly')}
			>
				<Text
					className={`text-white text-sm md:text-base font-medium ${billingCycle === 'monthly' ? 'font-semibold' : ''}`}
					style={billingCycle === 'monthly' ? { color: theme.colors.primary } : {}}
				>
					Monatlich
				</Text>
			</Pressable>
			<Pressable
				className={`flex-1 py-3 items-center rounded-md flex-row justify-center ${billingCycle === 'yearly' ? 'bg-[rgba(255,255,255,0.1)]' : ''}`}
				onPress={() => onChange('yearly')}
			>
				<Text
					className={`text-white text-sm md:text-base font-medium ${billingCycle === 'yearly' ? 'font-semibold' : ''}`}
					style={billingCycle === 'yearly' ? { color: theme.colors.primary } : {}}
				>
					Jährlich
				</Text>
				{yearlyDiscount && (
					<View
						className="bg-primary rounded-xl px-2 py-0.5 ml-2"
						style={{ backgroundColor: theme.colors.primary }}
					>
						<Text className="text-black text-[10px] md:text-xs font-bold">
							{yearlyDiscount} Rabatt
						</Text>
					</View>
				)}
			</Pressable>
		</View>
	);
};

export default BillingToggle;
