// maerchenzauber/apps/landing/src/components/ui/Button.tsx
import React, { useState } from 'react';

type ButtonVariant = 'primary' | 'secondary' | 'tonal' | 'plain';
type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps {
  children: React.ReactNode;
  variant?: ButtonVariant;
  size?: ButtonSize;
  onClick?: () => void;
  href?: string;
  disabled?: boolean;
  className?: string;
  icon?: React.ReactNode;
  iconPosition?: 'left' | 'right';
}

export default function Button({
  children,
  variant = 'primary',
  size = 'md',
  onClick,
  href,
  disabled = false,
  className = '',
  icon,
  iconPosition = 'right'
}: ButtonProps) {
  const [isHovered, setIsHovered] = useState(false);
  const [isPressed, setIsPressed] = useState(false);

  const baseStyles = 'inline-flex items-center justify-center font-semibold rounded-md transition-all duration-200';
  
  const variantStyles = {
    primary: 'bg-yellow-dark text-white hover:opacity-80 active:opacity-70',
    secondary: 'bg-transparent border border-yellow-dark text-yellow-dark hover:opacity-80 active:opacity-70',
    tonal: 'bg-yellow-dark/20 text-yellow-dark hover:bg-yellow-dark/30',
    plain: 'bg-transparent text-yellow-dark hover:text-yellow-light'
  };

  const sizeStyles = {
    sm: 'px-4 py-2 text-sm',
    md: 'px-6 py-3 text-base',
    lg: 'px-8 py-4 text-lg'
  };

  const combinedStyles = `${baseStyles} ${variantStyles[variant]} ${sizeStyles[size]} ${
    disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'
  } ${className}`;

  const content = (
    <>
      {icon && iconPosition === 'left' && (
        <span className="mr-2">{icon}</span>
      )}
      {children}
      {icon && iconPosition === 'right' && (
        <span className="ml-2">{icon}</span>
      )}
    </>
  );

  if (href) {
    return (
      <a
        href={href}
        className={combinedStyles}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        onMouseDown={() => setIsPressed(true)}
        onMouseUp={() => setIsPressed(false)}
      >
        {content}
      </a>
    );
  }

  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={combinedStyles}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onMouseDown={() => setIsPressed(true)}
      onMouseUp={() => setIsPressed(false)}
    >
      {content}
    </button>
  );
}

// apps/picture/apps/web-archived/src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	interface Props extends HTMLButtonAttributes {
		variant?: 'primary' | 'secondary' | 'danger';
		loading?: boolean;
		children?: Snippet;
	}

	let {
		variant = 'primary',
		loading = false,
		disabled,
		children,
		class: className,
		...rest
	}: Props = $props();

	const variantClasses: Record<string, string> = {
		primary: 'bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-300',
		secondary:
			'bg-gray-100 text-gray-700 hover:bg-gray-200 disabled:bg-gray-50 disabled:text-gray-400',
		danger: 'bg-red-600 text-white hover:bg-red-700 disabled:bg-red-300',
	};
</script>

<button
	class="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors disabled:cursor-not-allowed {variantClasses[
		variant
	]} {className ?? ''}"
	disabled={disabled || loading}
	{...rest}
>
	{#if loading}
		<div
			class="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-current border-r-transparent"
		></div>
	{/if}
	{#if children}
		{@render children()}
	{/if}
</button>
