// packages/shared-ui/src/molecules/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';

	interface Props {
		value: string;
		oninput?: (value: string) => void;
		onchange?: (value: string) => void;
		label?: string;
		placeholder?: string;
		type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
		error?: string;
		disabled?: boolean;
		required?: boolean;
		autocomplete?: HTMLInputAttributes['autocomplete'];
		class?: string;
	}

	let {
		value = $bindable(),
		oninput,
		onchange,
		label,
		placeholder,
		type = 'text',
		error,
		disabled = false,
		required = false,
		autocomplete,
		class: className = ''
	}: Props = $props();

	function handleInput(e: Event) {
		const target = e.target as HTMLInputElement;
		value = target.value;
		oninput?.(target.value);
	}

	function handleChange(e: Event) {
		const target = e.target as HTMLInputElement;
		onchange?.(target.value);
	}
</script>

<div class="flex flex-col gap-1.5 {className}">
	{#if label}
		<label class="text-sm font-medium text-theme">
			{label}
			{#if required}
				<span class="text-red-500">*</span>
			{/if}
		</label>
	{/if}
	
	<input
		{type}
		{value}
		{placeholder}
		{disabled}
		{required}
		autocomplete={autocomplete as HTMLInputAttributes['autocomplete']}
		oninput={handleInput}
		onchange={handleChange}
		class="w-full rounded-lg border px-4 py-2.5 text-theme bg-content transition-colors focus:outline-none focus:ring-2 focus:ring-primary/50 disabled:opacity-50 disabled:cursor-not-allowed {error
			? 'border-red-500 focus:ring-red-500/50'
			: 'border-theme'}"
	/>
	
	{#if error}
		<p class="text-sm text-red-500">{error}</p>
	{/if}
</div>

// apps-archived/maerchenzauber/apps/landing/src/components/ui/Input.tsx
import React, { useState } from 'react';

interface InputProps {
	type?: 'text' | 'email' | 'password' | 'number' | 'tel';
	placeholder?: string;
	value?: string;
	onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
	onFocus?: () => void;
	onBlur?: () => void;
	disabled?: boolean;
	required?: boolean;
	className?: string;
	icon?: React.ReactNode;
}

export default function Input({
	type = 'text',
	placeholder,
	value,
	onChange,
	onFocus,
	onBlur,
	disabled = false,
	required = false,
	className = '',
	icon,
}: InputProps) {
	const [isFocused, setIsFocused] = useState(false);

	const handleFocus = () => {
		setIsFocused(true);
		onFocus?.();
	};

	const handleBlur = () => {
		setIsFocused(false);
		onBlur?.();
	};

	return (
		<div className="relative">
			{icon && (
				<div className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary">{icon}</div>
			)}
			<input
				type={type}
				placeholder={placeholder}
				value={value}
				onChange={onChange}
				onFocus={handleFocus}
				onBlur={handleBlur}
				disabled={disabled}
				required={required}
				className={`
          w-full bg-bg-input rounded-lg text-text-primary 
          px-3 py-3 text-base border-none outline-none
          placeholder:text-text-muted
          focus:ring-2 focus:ring-yellow-dark
          disabled:opacity-50 disabled:cursor-not-allowed
          transition-all duration-200
          ${icon ? 'pl-10' : ''}
          ${className}
        `}
			/>
		</div>
	);
}
