// apps/picture/apps/web/src/lib/components/ui/Input.svelte
<script lang="ts">
	interface Props {
		type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
		value?: string;
		placeholder?: string;
		label?: string;
		error?: string;
		disabled?: boolean;
		required?: boolean;
		class?: string;
		id?: string;
		name?: string;
		autocomplete?: string;
		onchange?: (e: Event) => void;
		oninput?: (e: Event) => void;
	}

	let {
		type = 'text',
		value = $bindable(''),
		placeholder = '',
		label = '',
		error = '',
		disabled = false,
		required = false,
		class: className = '',
		id = '',
		name = '',
		autocomplete = '',
		onchange,
		oninput
	}: Props = $props();

	const inputId = id || name || `input-${Math.random().toString(36).substr(2, 9)}`;

	const baseStyles =
		'flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';

	const errorStyles = error ? 'border-red-500 focus:ring-red-600' : '';

	const inputClass = `${baseStyles} ${errorStyles} ${className}`;
</script>

{#if label}
	<label for={inputId} class="mb-2 block text-sm font-medium text-gray-700">
		{label}
		{#if required}
			<span class="text-red-500">*</span>
		{/if}
	</label>
{/if}

<input
	{type}
	bind:value
	{placeholder}
	{disabled}
	{required}
	{name}
	{autocomplete}
	id={inputId}
	class={inputClass}
	onchange={onchange}
	oninput={oninput}
/>

{#if error}
	<p class="mt-1 text-sm text-red-600">{error}</p>
{/if}

// apps-archived/maerchenzauber/apps/landing/src/components/ui/Input.tsx
import React, { useState } from 'react';

interface InputProps {
	type?: 'text' | 'email' | 'password' | 'number' | 'tel';
	placeholder?: string;
	value?: string;
	onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
	onFocus?: () => void;
	onBlur?: () => void;
	disabled?: boolean;
	required?: boolean;
	className?: string;
	icon?: React.ReactNode;
}

export default function Input({
	type = 'text',
	placeholder,
	value,
	onChange,
	onFocus,
	onBlur,
	disabled = false,
	required = false,
	className = '',
	icon,
}: InputProps) {
	const [isFocused, setIsFocused] = useState(false);

	const handleFocus = () => {
		setIsFocused(true);
		onFocus?.();
	};

	const handleBlur = () => {
		setIsFocused(false);
		onBlur?.();
	};

	return (
		<div className="relative">
			{icon && (
				<div className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary">{icon}</div>
			)}
			<input
				type={type}
				placeholder={placeholder}
				value={value}
				onChange={onChange}
				onFocus={handleFocus}
				onBlur={handleBlur}
				disabled={disabled}
				required={required}
				className={`
          w-full bg-bg-input rounded-lg text-text-primary 
          px-3 py-3 text-base border-none outline-none
          placeholder:text-text-muted
          focus:ring-2 focus:ring-yellow-dark
          disabled:opacity-50 disabled:cursor-not-allowed
          transition-all duration-200
          ${icon ? 'pl-10' : ''}
          ${className}
        `}
			/>
		</div>
	);
}
